repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-merge-conflicts
    -   id: end-of-file-fixer
        exclude:
            requirements.txt
    -   id: trailing-whitespace
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    -   id: black
